### ISSUE TITLE
Target .NET Standard 2.0

### ISSUE THREAD

**Issue by bobted** [ChangemakerStudios/Serilog.Enricher.WhenDo#1]
Any chance to update the target frameworks to include .NET Standard 2.0?

**Comment by Jaben** [comment]
Absolutely.

**Comment by Jaben** [comment]
Done. Please test! :)

**Comment by bobted** [comment]
Seems to work. I was able to pull the package in and build. VS no longer complains that it was using a full framework package. After the build, the functionality appears to be the same.

Thanks for the quick turn around.
